version: '3.1'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        volumes:
        - .:/usr/app
        depends_on:
        - redis
    redis:
        image: redis:alpine
